services:
  nagios:
    image: lscr.io/linuxserver/nagios:latest
    container_name: nagios_container
    ports:
      - "8081:80"
      - "5666:5666"
    networks:
      - HNJN

networks:
  HNJN:
    external: true
